sudo: false
addons:
  sonarcloud:
    token: ${SONAR_TOKEN}
jdk:
  - openjdk11
languaje: java
script: 
  -mvn test -f ejemplomavenIC/pom.xml
  -sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=aaronmv3 -Dsonar.proyectKJey=ejemploIC